/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package valonnue.javaproject.forms;

import hr.algebra.utilities.HashingUtils;
import hr.algebra.utilities.MessageUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import valonnue.javaproject.Models.User;
import valonnue.javaproject.dao.sql.SqlRepository;

/**
 *
 * @author valon
 */
public class AuthenticationPanels extends javax.swing.JFrame {

    /**
     * Creates new form AuthenticationPanels
     */
    public AuthenticationPanels() {
        initComponents();
        hideErrors();
    }

    private enum AdminCredentials {
        USERNAME("admin"),
        PASSWORD("admin");

        private final String value;

        private AdminCredentials(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return value;
        }
    }
    private final SqlRepository db = new SqlRepository();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tfRegisterFirstName1 = new javax.swing.JTextField();
        lbErrorRegisterFirstName1 = new javax.swing.JLabel();
        tpAuthentication = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnDontHaveAnAccount = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfLoginUsername = new javax.swing.JTextField();
        lbErrorLoginUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbErrorLoginPassword = new javax.swing.JLabel();
        pwfLogin = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnAlreadyHaveAnAccount = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfRegisterUsername = new javax.swing.JTextField();
        lbErrorRegisterUsername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfRegisterFirstName = new javax.swing.JTextField();
        lbErrorRegisterFirstName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfRegisterLastName = new javax.swing.JTextField();
        lbErrorRegisterLastName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbErrorRegisterPassword = new javax.swing.JLabel();
        pwfRegister = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        pwfRegisterConfirm = new javax.swing.JPasswordField();
        lbErrorRegisterPasswordConfirm = new javax.swing.JLabel();

        jLabel5.setText("First Name");

        lbErrorRegisterFirstName1.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorRegisterFirstName1.setText("!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDontHaveAnAccount.setText("I do not have an account");
        btnDontHaveAnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDontHaveAnAccountActionPerformed(evt);
            }
        });

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        lbErrorLoginUsername.setForeground(new java.awt.Color(153, 0, 0));
        lbErrorLoginUsername.setText("!");

        jLabel2.setText("Password:");

        lbErrorLoginPassword.setForeground(new java.awt.Color(153, 0, 0));
        lbErrorLoginPassword.setText("!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbErrorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDontHaveAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbErrorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErrorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwfLogin)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbErrorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDontHaveAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(202, 202, 202))
        );

        tpAuthentication.addTab("Log In", jPanel1);

        btnAlreadyHaveAnAccount.setText("I already have an account!");
        btnAlreadyHaveAnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlreadyHaveAnAccountActionPerformed(evt);
            }
        });

        btnRegister.setText("Create Account");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel3.setText("Username:");

        lbErrorRegisterUsername.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorRegisterUsername.setText("!");

        jLabel4.setText("First Name:");

        lbErrorRegisterFirstName.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorRegisterFirstName.setText("!");

        jLabel6.setText("Last Name:");

        lbErrorRegisterLastName.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorRegisterLastName.setText("!");

        jLabel7.setText("Password:");

        lbErrorRegisterPassword.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorRegisterPassword.setText("!");

        jLabel8.setText("Confirm Password:");

        lbErrorRegisterPasswordConfirm.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorRegisterPasswordConfirm.setText("!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnAlreadyHaveAnAccount)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(39, 39, 39)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfRegisterUsername)
                                        .addComponent(tfRegisterFirstName)
                                        .addComponent(tfRegisterLastName)
                                        .addComponent(pwfRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbErrorRegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbErrorRegisterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbErrorRegisterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbErrorRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(pwfRegisterConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbErrorRegisterPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbErrorRegisterUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRegisterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErrorRegisterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRegisterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErrorRegisterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErrorRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwfRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErrorRegisterPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwfRegisterConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlreadyHaveAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        tpAuthentication.addTab("Register", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAuthentication)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAuthentication, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tpAuthentication.getAccessibleContext().setAccessibleName("tpAuthentication");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDontHaveAnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDontHaveAnAccountActionPerformed
        // TODO add your handling code here:
        tpAuthentication.setSelectedIndex(1);
    }//GEN-LAST:event_btnDontHaveAnAccountActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        hideErrors();
        if (!loginFormIsValid()) {
            return;
        }
        String username = tfLoginUsername.getText();
        String password = getTextFromPassword(pwfLogin.getPassword());
        //Check if Admin
        /*<Admin credentials>
           <Username> admin </Username>
           <Password> admin <Password/>
        </Admin credentials>*/
        if (username.equals(AdminCredentials.USERNAME.toString()) && password.equals(AdminCredentials.PASSWORD.toString())) {
            //Return admin form
            AdminForm adminForm = new AdminForm();
            adminForm.setVisible(true);
            dispose();
            return;
        }
        //Log In
        try {
            if (!userExists(username)) {
                MessageUtils.showErrorMessage("Unknown user", "No user exists with such username");
                return;
            }
            User user = db.selectUsers().stream()
                    .filter(optionalUser -> optionalUser.getUsername().equals(username))
                    .findFirst()
                    .orElse(null);
            if (!HashingUtils.checkPassword(password, user.getPasswordHash())) {
                MessageUtils.showErrorMessage("Wrong password", "You might have mistyped your password");
                return;
            }
            UserForm userForm = new UserForm();
            userForm.setVisible(true);
            dispose();

        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", ex.getMessage());
        }


    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnAlreadyHaveAnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlreadyHaveAnAccountActionPerformed
        // TODO add your handling code here:
        tpAuthentication.setSelectedIndex(0);
    }//GEN-LAST:event_btnAlreadyHaveAnAccountActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        hideErrors();
        if (!registerFormIsValid()) {
            return;
        }
        String username = tfRegisterUsername.getText().trim().toLowerCase();
        String firstName = tfRegisterFirstName.getText();
        String lastName = tfRegisterLastName.getText();
        //Turn the password into unreadable by the human
        String hashedPassword = "";
        try {
            hashedPassword = HashingUtils.hashPassword(getTextFromPassword(pwfRegister.getPassword()));
        } catch (Exception ex) {
            Logger.getLogger(AuthenticationPanels.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        //Check if such user already exists
        try {
            if (userExists(username)) {
                MessageUtils.showErrorMessage("Username is taken", "That username is taken");
                return;
            }
            //Save the User in the database
            int id = db.createUser(new User(username, hashedPassword, firstName, lastName));
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Not good", ex.getMessage());
            return;
        }

        //Return to the login page
        tfLoginUsername.setText(username);
        pwfLogin.setText(getTextFromPassword(pwfRegister.getPassword()));
        tpAuthentication.setSelectedIndex(0);

        clearRegisteringFields();

    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationPanels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationPanels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationPanels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationPanels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationPanels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlreadyHaveAnAccount;
    private javax.swing.JButton btnDontHaveAnAccount;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbErrorLoginPassword;
    private javax.swing.JLabel lbErrorLoginUsername;
    private javax.swing.JLabel lbErrorRegisterFirstName;
    private javax.swing.JLabel lbErrorRegisterFirstName1;
    private javax.swing.JLabel lbErrorRegisterLastName;
    private javax.swing.JLabel lbErrorRegisterPassword;
    private javax.swing.JLabel lbErrorRegisterPasswordConfirm;
    private javax.swing.JLabel lbErrorRegisterUsername;
    private javax.swing.JPasswordField pwfLogin;
    private javax.swing.JPasswordField pwfRegister;
    private javax.swing.JPasswordField pwfRegisterConfirm;
    private javax.swing.JTextField tfLoginUsername;
    private javax.swing.JTextField tfRegisterFirstName;
    private javax.swing.JTextField tfRegisterFirstName1;
    private javax.swing.JTextField tfRegisterLastName;
    private javax.swing.JTextField tfRegisterUsername;
    private javax.swing.JTabbedPane tpAuthentication;
    // End of variables declaration//GEN-END:variables

//    private final List<JLabel> ERROR_LABELS = new List<>()(lbErrorLoginUsername, lbErrorLoginPassword, lbErrorRegisterUsername, lbErrorRegisterFirstName, lbErrorRegisterLastName, lbErrorRegisterPassword, lbErrorRegisterPasswordConfirm};
    private void init() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void hideErrors() {
        /* for (JLabel error : ERROR_LABELS) {
            if (error != null) error.setVisible(false);
        }*/
        lbErrorLoginUsername.setVisible(false);
        lbErrorLoginPassword.setVisible(false);
        lbErrorRegisterUsername.setVisible(false);
        lbErrorRegisterFirstName.setVisible(false);
        lbErrorRegisterLastName.setVisible(false);
        lbErrorRegisterPassword.setVisible(false);
        lbErrorRegisterPasswordConfirm.setVisible(false);
    }

    private static String getTextFromPassword(char[] password) {
        String result = "";
        for (int i = 0; i < password.length; i++) {
            result += password[i];
        }
        return result;
    }

    private boolean registerFormIsValid() {
        if (tfRegisterUsername
                .getText()
                .trim()
                .toLowerCase()
                .length() < 6) {
            lbErrorRegisterUsername.setVisible(true);
            MessageUtils.showErrorMessage("Username too short", "Username should be 6 or more charachters long");
            return false;
        }
        if (tfRegisterFirstName.getText().isEmpty()) {
            lbErrorRegisterFirstName.setVisible(true);
            MessageUtils.showErrorMessage("Write your name", "First Name can not be empty");
            return false;
        }
        if (tfRegisterLastName.getText().isEmpty()) {
            lbErrorRegisterLastName.setVisible(true);
            MessageUtils.showErrorMessage("Write your name", "Last Name can not be empty");
            return false;
        }
        if (getTextFromPassword(pwfRegister.getPassword()).length() < 6) {
            lbErrorRegisterPassword.setVisible(true);
            MessageUtils.showErrorMessage("Password too short", "Password should be a minimum of 6 charachters long");
            return false;
        }
        if (!getTextFromPassword(pwfRegister.getPassword()).equals(getTextFromPassword(pwfRegisterConfirm.getPassword()))) {
            lbErrorRegisterPasswordConfirm.setVisible(true);
            MessageUtils.showErrorMessage("Passwords do not match", "Passwords in the `Password` and `Confirm Password` should match.");
            return false;
        }
        return true;

    }

    private void clearRegisteringFields() {
        tfRegisterUsername.setText("");
        tfRegisterFirstName.setText("");
        tfRegisterLastName.setText("");
        pwfRegister.setText("");
        pwfRegisterConfirm.setText("");
    }

    private boolean loginFormIsValid() {
        if (tfLoginUsername.getText().isEmpty()) {
            MessageUtils.showErrorMessage("Empty Username", "You can not try to log in with an empty username");
            lbErrorLoginUsername.setVisible(true);
            return false;
        }
        if (getTextFromPassword(pwfLogin.getPassword()).isEmpty()) {
            MessageUtils.showErrorMessage("Empty Password", "You can not try to log in without entering your password");
            lbErrorLoginPassword.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean userExists(String username) throws Exception {
        return db.selectUsers().stream()
                .anyMatch(user -> user.getUsername().equals(username));
    }

}
